# Generated by Django 3.2.3 on 2021-08-12 15:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.IntegerField(max_length=10)),
                ('date', models.DateTimeField(default=datetime.date(2021, 8, 12))),
                ('message', models.CharField(max_length=500)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department')),
            ],
        ),
        migrations.CreateModel(
            name='Appoiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.date(2021, 8, 12))),
                ('num', models.IntegerField(max_length=50)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.docter')),
            ],
        ),
    ]
