# Generated by Django 3.2.3 on 2021-08-17 14:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appoiment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoiment',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='appoiment',
            name='num',
        ),
        migrations.AlterField(
            model_name='appoiment',
            name='date',
            field=models.DateTimeField(default=datetime.date(2021, 8, 17)),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='date',
            field=models.DateTimeField(default=datetime.date(2021, 8, 17)),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('app_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appoiment.appoiment')),
            ],
        ),
    ]
