# Generated by Django 3.2.3 on 2021-08-20 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoiment', '0002_auto_20210817_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoiment',
            name='date',
            field=models.DateTimeField(default=datetime.date(2021, 8, 21)),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='date',
            field=models.DateTimeField(default=datetime.date(2021, 8, 21)),
        ),
    ]
